spring:
  config:
    import: optional:classpath:.env[.properties]
  application:
    name: user-service
  web:
    error:
      include-stacktrace: NEVER
  # Configurando a conexao com o banco de dados
  datasource:
    # Criando a conexao com o banco de dados, definindo o timezone para ecitar problemas e criando banco se ele nao existir
    url: jdbc:mysql://localhost:3306/user_service?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${ENV_ROOT_USER}
    password: ${ENV_ROOT_PASSWORD}
  jpa:
    # Mostra todas as querys da funcao no meu terminal
    show-sql: true
    # Consigo rodar a aplicacao e criar as tabelas automaticamente no banco de dados (nao utilizado em producao)
    hibernate:
      ddl-auto: update
  threads:
    virtual:
      enabled: true

logging:
  level:
    academy.devdojo: debug
    # Mostra quais são os parametros utilizados nas querys do banco de dados ao fazer uma chamada no postman
    # Não é utilizado em produção
    # org.hibernate.orm.jdbc.bind: trace
#    net.ttddyy.dsproxy.listener.logging.SLF4JQueryLoggingListener: debug
#    net.ttddyy.dsproxy.listener.logging.SLF4JSlowQueryListener: warn
#decorator:
#  datasource:
#    datasource-proxy:
#      query:
#        enable-logging: true
#        log-level: debug
#      slow-query:
#        enable-logging: true
#        log-level: warn

server:
  servlet:
    context-path: /
  port: 8090

  tomcat:
    threads:
      max: 20