insert into tb_user (email, first_name, last_name, id) values ('carlos@gmail.com','Carlos','Soares',1)
insert into tb_user (email, first_name, last_name, id) values ('ana@gmail.com','Ana','Silva',2)
insert into profile (id, description, name) values (1,'Perfil Administrador','Administrador')
insert into user_profile (id, profile_id, user_id) values (1, 1, 1)
insert into user_profile (id, profile_id, user_id) values (2, 1, 2)